[front]: link with app id in clever cloud (#326)

diff --git a/.github/workflows/review.yml b/.github/workflows/review.yml
--- a/.github/workflows/review.yml
+++ b/.github/workflows/review.yml
@@ -82,12 +82,16 @@ jobs:
           clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
           APP_ALIAS=${{ github.event.repository.name }}-PR-${{ github.event.number }}
 
-          clever create --type node $APP_ALIAS \
-            --alias $APP_ALIAS \
-            --region par \
-            --org ${{ secrets.ORGA_ID }} || echo "App may already exist"
+          clever create --type node $APP_ALIAS --alias $APP_ALIAS --region par --org ${{ secrets.ORGA_ID }} || echo "App may already exist"
 
-          clever link --alias $APP_ALIAS
+          APP_ID=$(clever apps --json | jq -r ".[] | select(.alias==\"$APP_ALIAS\") | .id")
+
+          if [ -z "$APP_ID" ]; then
+            echo "Failed to get app ID for alias $APP_ALIAS"
+            exit 1
+          fi
+
+          clever link "$APP_ID"
 
           for var in $(env | awk -F= '/^GH_/ { print $1 }'); do
             real_var=${var#GH_}
